version: "3.7"
services:
  app:
    build:
      args:
        user: fredrick
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pet-store
    container_name: pet-store-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - petstore

  db:
    image: mysql:8.0
    container_name: pet-store-db
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - petstore

  nginx:
    image: nginx:alpine
    container_name: pet-store-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - petstore

networks:
  petstore:
    driver: bridge
